### ISSUE TITLE
USER STORY: Django Setup

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#1]
## Epic: Installations / Setup

***
As a **Developer**, I can **set us Django and libraries**, so that **I can create apps to develop the site**.

## Acceptance Criteria
- Install Django and other libraries
- Check out for the Django setup success page when running the server

## Task
- [x] Django/Libraries Install.
- [x] Install predicted libraries based on Boutique Ado Walkthrough
- [x] Create a requirements.txt file
- [x] Freeze requirements.txt file
