### ISSUE TITLE
USER STORY: View shopping Bag / Cart

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#10]
## Epic: Purchase / Checkout

***
As a **User**, I can **view all selected items in my bag/cart**, so that **I can manage items and proceed to purchase**.

## Acceptance Criteria
- Users can view the cart/bag so as to manage the selected list (CRUD)

## Task
- [x] Create a Cart Template
- [x] Add a styling inline with the site theme
- [x] Add Update and delete functions
- [x] Add a form to select the quantity of a specific item
- [x] Add button to proceed to the details and payment page
