### ISSUE TITLE
USER STORY: Checkout-Details

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#12]
## Epic: Purchase / Checkout

***
As a **User**, I can **enter my details and checkout**, so that **my order will be processed as a buy**.

## Acceptance Criteria
- User can view a detailed form to fill in details for the order
- The user cannot complete the process unless all required fields are filled
- The user must be able to enter payment details to pay for the order 
- The user must be able to receive an order confirmation on screen and also per email

## Task
- [x] Create checkout models, URLs and views
- [x] Create payment information forms
- [x] Create a stripe payment system to allow user to pay with MasterCard/Visa
- [x] Create an automatic Email system to send messages to user/shoppers for their order(s).
- [x] Create Stock control
