### ISSUE TITLE
USER STORY: Message and Toast

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#13]
## Epic: UX/UI design

***
As a **User**, I must **be able to be notified with messages**, so that **I would know if my request is successful.**.

## Acceptance Criteria
- Messages display when the user carries out an action that has a corresponding message in the view

## Task
- [x] Create toast templates and style them
- [x] Update in base.HTML
- [x] Create messages in the views
- [x] Link toast with messages
