### ISSUE TITLE
USER STORY: User Profile

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#14]
## Epic : User Profile

***
As a **User/Customer**, I can **create a user profile/account**, so that **I can access additional user features**.

## Acceptance Criteria
- User/Customer can register with sign-up forms and login in.
- Log-in users/customers must have access to a User account profiles
- The user profile must display information like the user details and also order details

## Task
- [x] Create a user profile page
- [x] Create a user profile forms for users to store data that links to the shipping data
- [x] Create a view for the orders made by the user
