### ISSUE TITLE
USER STORY: Contact Us page

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#15]
## Epic :  Contact/Information

***
As a **user**, I can **access contact forms**, so that **reach our to shop owner for more information**.

## Acceptance Criteria
- Users/Customers can contact the shop owner through the contact page

## Task
- [x] Create a contact us page
- [x] Create contact forms with validations
- [x] Link to an Email to receive messages being sent.
