### ISSUE TITLE
USER STORY: SEO Implementation

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#17]
## Epic: SEO Implementation

***
As a **Developer** I can **add helpful descriptions and keywords** so that **my site can reach a wider audience**.

## Acceptance Criteria
- Add site short tail/long tail keywords

## Task
- [x] Signup to Wordtracker
- [x] Research keyword phrases
- [x] Implement keywords into code
