### ISSUE TITLE
USER STORY: Setup AWS

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#2]
## Epic: Installations / Setup

***
As a **Developer**, I can **set up AWS**, so that **I can store all static and media files**.

## Acceptance Criteria
- When the site is deployed static and media files are displayed 
as expected site

## Task
- [x] Create a new bucket
- [x] Connect S3 to Django
- [x] Create AWS Groups.
- [x] Create AWS Policies and Users.
