### ISSUE TITLE
USER STORY: Base/Static Template 

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#4]
## Epic: UX/UI design

***
As a **Developer**, I can **set up base templates and statics**, so that **I can extend them to pages easily**.

## Acceptance Criteria
- When the template is extended to another template all HTML code is applied i.e. Navbar/Footer

## Task
- [x] Set up the base.html.
- [x] Extend all other pages for UX.
- [x] Create a static folder to contain CSS and JS folders and files
- [x] Create base and static folders and files for each app for easy access
