### ISSUE TITLE
USER STORY: Homepage / Site Navigation

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#5]
## Epic: UX/UI Design

***
As a **User**, I can **easily navigate between the sites pages**, so that **I can find what I am looking for.**.

## Acceptance Criteria
- Uniform navigation tabs on each page of the site
- All navigation links were manually tested for all pages and working as intended
- E-commerce Hero section with Shop Now button working.
- Some product feature showcase
- Testimonials section
- Footer with New letter forms and subscribe button

## Task
- [x] Create a site header
- [x] Create Hero section content with a Shop Now button to link all products
- [ ] Create a featured product section
- [x]  Create a footer with contact details, social link and newsletter form.
