### ISSUE TITLE
USER STORY: Setup Allauth for all authorizations

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#6]
## Epic: Authorization and Authentication

***
As a **Admin/Site User**, I can **register an account **, so that **I can have access to some features**.

## Acceptance Criteria
- User can sign in after registering with Username, Email and Password
- The user should not be able to register the same username or email address more than once
- User can now have access to the order and profile feature
- Admin can have access to add, edit and remove products (CRUD)

## Task
- [x] Sign Up/Login/Logout
- [ ] Login with a Google link
- [x] Email Verification
- [x] Password Reset
- [x] Style All AUTH Templates
