### ISSUE TITLE
USER STORY: Setup the product app

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#7]
## Epic: Product Setup

***
As a **Admin/Site User**, I can **have access to the products **, so that **I can view details and select them**.

## Acceptance Criteria
- Users can view all products and also in different categories
- The user should not be able to access the product detail page and also be able to select product, quantity and size for purchase.
- The selected product should be added to the cart/bag

## Task
- [x] Create the products and categories.
- [x] Set up products to display on the site.
- [x] User to access the product detail page by clicking on the product.
- [x] Allow product to be added to the cart for purchase.
- [ ] Create Wishlist for users to save product for future
