### ISSUE TITLE
USER STORY: Setup the product CRUD

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#8]
## Epic: Product Setup

***
As a **Admin**, I can **be to access product management**, so that **I can add, edit and remove products**.

## Acceptance Criteria
- Provide product management link if logged in as Admin/Staff
- Admin must be able to add, edit and remove products from frontend

## Task
- [x] Add product function
- [x] Edit product function
- [x] Delete product function
