### ISSUE TITLE
USER STORY: Product sorting

### ISSUE THREAD

**Issue by Benohene** [Benohene/pb_majestic_cloding#9]
## Epic: Product Setup

***
As a **User/customer**, I can **be able to sort the product easily**, so that **I can easily find a product easily**.

## Acceptance Criteria
- User/Customer can have access to a sorting box
- User/Customer can select sorting according to price, name, rating and category
- User/Customer can sort out in both ascending and descending direction

## Task
- [x] Add a product sorting form with options to select.
- [x] Setup product sorting with name, category, price and ratings.
- [x] Setup up sorting in descending and ascending order.
